/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.contraintesColonnes.ui.internal.ContraintesColonnesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CONTRAINTESUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ContraintesColonnesActivator.getInstance().getInjector("fr.n7.CONTRAINTES");
	}

}
