<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Tableur" nsURI="http://tableur" nsPrefix="tableur">
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonnes" lowerBound="1"
        upperBound="-1" eType="#//ColonneDonnee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="colonneID" lowerBound="1"
        eType="#//ColonneID"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Colonne" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Primitive"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonneeBrute" eSuperTypes="#//ColonneDonnee"/>
  <eClassifiers xsi:type="ecore:EClass" name="DonneeCalculee" eSuperTypes="#//ColonneDonnee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fonction" eType="ecore:EClass ../../fr.n7.Traitement/model/Traitement.ecore#//Fonction"
        eOpposite="../../fr.n7.Traitement/model/Traitement.ecore#//Fonction/sorties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Primitive">
    <eLiterals name="integer"/>
    <eLiterals name="string" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneID" eSuperTypes="#//Colonne"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColonneDonnee" eSuperTypes="#//Colonne"/>
</ecore:EPackage>
