/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES.tests;

import fr.n7.cONTRAINTES.CONTRAINTESFactory;
import fr.n7.cONTRAINTES.Comparaison;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Comparaison</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ComparaisonTest extends ExpressionTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ComparaisonTest.class);
	}

	/**
	 * Constructs a new Comparaison test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComparaisonTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Comparaison test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Comparaison getFixture() {
		return (Comparaison)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CONTRAINTESFactory.eINSTANCE.createComparaison());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ComparaisonTest
