/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>CONTRAINTES</b></em>' model.
 * <!-- end-user-doc -->
 * @generated
 */
public class CONTRAINTESAllTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new CONTRAINTESAllTests("CONTRAINTES Tests");
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CONTRAINTESAllTests(String name) {
		super(name);
	}

} //CONTRAINTESAllTests
