/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>cONTRAINTES</b></em>' package.
 * <!-- end-user-doc -->
 * @generated
 */
public class CONTRAINTESTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new CONTRAINTESTests("cONTRAINTES Tests");
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CONTRAINTESTests(String name) {
		super(name);
	}

} //CONTRAINTESTests
