/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES.tests;

import fr.n7.cONTRAINTES.CONTRAINTESFactory;
import fr.n7.cONTRAINTES.EnsembleContraintes;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Ensemble Contraintes</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class EnsembleContraintesTest extends TestCase {

	/**
	 * The fixture for this Ensemble Contraintes test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnsembleContraintes fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(EnsembleContraintesTest.class);
	}

	/**
	 * Constructs a new Ensemble Contraintes test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EnsembleContraintesTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Ensemble Contraintes test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(EnsembleContraintes fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Ensemble Contraintes test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnsembleContraintes getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CONTRAINTESFactory.eINSTANCE.createEnsembleContraintes());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //EnsembleContraintesTest
