/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES.tests;

import fr.n7.cONTRAINTES.CONTRAINTESFactory;
import fr.n7.cONTRAINTES.OperationUnaire;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Operation Unaire</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class OperationUnaireTest extends ExpressionTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(OperationUnaireTest.class);
	}

	/**
	 * Constructs a new Operation Unaire test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public OperationUnaireTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Operation Unaire test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected OperationUnaire getFixture() {
		return (OperationUnaire)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(CONTRAINTESFactory.eINSTANCE.createOperationUnaire());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //OperationUnaireTest
