/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparaison</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.cONTRAINTES.Comparaison#getComparateur <em>Comparateur</em>}</li>
 *   <li>{@link fr.n7.cONTRAINTES.Comparaison#getConstante <em>Constante</em>}</li>
 * </ul>
 *
 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getComparaison()
 * @model
 * @generated
 */
public interface Comparaison extends Expression
{
  /**
   * Returns the value of the '<em><b>Comparateur</b></em>' attribute.
   * The literals are from the enumeration {@link fr.n7.cONTRAINTES.ComparateurType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparateur</em>' attribute.
   * @see fr.n7.cONTRAINTES.ComparateurType
   * @see #setComparateur(ComparateurType)
   * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getComparaison_Comparateur()
   * @model
   * @generated
   */
  ComparateurType getComparateur();

  /**
   * Sets the value of the '{@link fr.n7.cONTRAINTES.Comparaison#getComparateur <em>Comparateur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparateur</em>' attribute.
   * @see fr.n7.cONTRAINTES.ComparateurType
   * @see #getComparateur()
   * @generated
   */
  void setComparateur(ComparateurType value);

  /**
   * Returns the value of the '<em><b>Constante</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constante</em>' attribute.
   * @see #setConstante(float)
   * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getComparaison_Constante()
   * @model
   * @generated
   */
  float getConstante();

  /**
   * Sets the value of the '{@link fr.n7.cONTRAINTES.Comparaison#getConstante <em>Constante</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constante</em>' attribute.
   * @see #getConstante()
   * @generated
   */
  void setConstante(float value);

} // Comparaison
