/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.cONTRAINTES.CONTRAINTESFactory
 * @model kind="package"
 * @generated
 */
public interface CONTRAINTESPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "cONTRAINTES";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.n7.fr/CONTRAINTES";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "cONTRAINTES";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  CONTRAINTESPackage eINSTANCE = fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl.init();

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.EnsembleContraintesImpl <em>Ensemble Contraintes</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.EnsembleContraintesImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getEnsembleContraintes()
	 * @generated
	 */
  int ENSEMBLE_CONTRAINTES = 0;

  /**
	 * The feature id for the '<em><b>Contraintes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENSEMBLE_CONTRAINTES__CONTRAINTES = 0;

  /**
	 * The number of structural features of the '<em>Ensemble Contraintes</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENSEMBLE_CONTRAINTES_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.ContrainteImpl <em>Contrainte</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.ContrainteImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getContrainte()
	 * @generated
	 */
  int CONTRAINTE = 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONTRAINTE__NAME = 0;

  /**
	 * The feature id for the '<em><b>Colonnes</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONTRAINTE__COLONNES = 1;

  /**
	 * The feature id for the '<em><b>Expression</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONTRAINTE__EXPRESSION = 2;

  /**
	 * The number of structural features of the '<em>Contrainte</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int CONTRAINTE_FEATURE_COUNT = 3;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.ColonneImpl <em>Colonne</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.ColonneImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getColonne()
	 * @generated
	 */
  int COLONNE = 2;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int COLONNE__NAME = 0;

  /**
	 * The number of structural features of the '<em>Colonne</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int COLONNE_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.ExpressionImpl <em>Expression</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.ExpressionImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getExpression()
	 * @generated
	 */
  int EXPRESSION = 3;

  /**
	 * The number of structural features of the '<em>Expression</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.ComparaisonImpl <em>Comparaison</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.ComparaisonImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getComparaison()
	 * @generated
	 */
  int COMPARAISON = 4;

  /**
	 * The feature id for the '<em><b>Comparateur</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int COMPARAISON__COMPARATEUR = EXPRESSION_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Constante</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int COMPARAISON__CONSTANTE = EXPRESSION_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Comparaison</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int COMPARAISON_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.OperationBinaireImpl <em>Operation Binaire</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.OperationBinaireImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperationBinaire()
	 * @generated
	 */
  int OPERATION_BINAIRE = 5;

  /**
	 * The feature id for the '<em><b>Contrainte Gauche</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_BINAIRE__CONTRAINTE_GAUCHE = EXPRESSION_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Operande</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_BINAIRE__OPERANDE = EXPRESSION_FEATURE_COUNT + 1;

  /**
	 * The feature id for the '<em><b>Contrainte Droite</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_BINAIRE__CONTRAINTE_DROITE = EXPRESSION_FEATURE_COUNT + 2;

  /**
	 * The number of structural features of the '<em>Operation Binaire</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_BINAIRE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.impl.OperationUnaireImpl <em>Operation Unaire</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.impl.OperationUnaireImpl
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperationUnaire()
	 * @generated
	 */
  int OPERATION_UNAIRE = 6;

  /**
	 * The feature id for the '<em><b>Operande</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_UNAIRE__OPERANDE = EXPRESSION_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Contrainte</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_UNAIRE__CONTRAINTE = EXPRESSION_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Operation Unaire</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OPERATION_UNAIRE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.ComparateurType <em>Comparateur Type</em>}' enum.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.ComparateurType
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getComparateurType()
	 * @generated
	 */
  int COMPARATEUR_TYPE = 7;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.OperandeBinaireType <em>Operande Binaire Type</em>}' enum.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.OperandeBinaireType
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperandeBinaireType()
	 * @generated
	 */
  int OPERANDE_BINAIRE_TYPE = 8;

  /**
	 * The meta object id for the '{@link fr.n7.cONTRAINTES.OperandeUnaireType <em>Operande Unaire Type</em>}' enum.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see fr.n7.cONTRAINTES.OperandeUnaireType
	 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperandeUnaireType()
	 * @generated
	 */
  int OPERANDE_UNAIRE_TYPE = 9;


  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.EnsembleContraintes <em>Ensemble Contraintes</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Ensemble Contraintes</em>'.
	 * @see fr.n7.cONTRAINTES.EnsembleContraintes
	 * @generated
	 */
  EClass getEnsembleContraintes();

  /**
	 * Returns the meta object for the containment reference list '{@link fr.n7.cONTRAINTES.EnsembleContraintes#getContraintes <em>Contraintes</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Contraintes</em>'.
	 * @see fr.n7.cONTRAINTES.EnsembleContraintes#getContraintes()
	 * @see #getEnsembleContraintes()
	 * @generated
	 */
  EReference getEnsembleContraintes_Contraintes();

  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.Contrainte <em>Contrainte</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Contrainte</em>'.
	 * @see fr.n7.cONTRAINTES.Contrainte
	 * @generated
	 */
  EClass getContrainte();

  /**
	 * Returns the meta object for the attribute '{@link fr.n7.cONTRAINTES.Contrainte#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see fr.n7.cONTRAINTES.Contrainte#getName()
	 * @see #getContrainte()
	 * @generated
	 */
  EAttribute getContrainte_Name();

  /**
	 * Returns the meta object for the containment reference list '{@link fr.n7.cONTRAINTES.Contrainte#getColonnes <em>Colonnes</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Colonnes</em>'.
	 * @see fr.n7.cONTRAINTES.Contrainte#getColonnes()
	 * @see #getContrainte()
	 * @generated
	 */
  EReference getContrainte_Colonnes();

  /**
	 * Returns the meta object for the containment reference list '{@link fr.n7.cONTRAINTES.Contrainte#getExpression <em>Expression</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Expression</em>'.
	 * @see fr.n7.cONTRAINTES.Contrainte#getExpression()
	 * @see #getContrainte()
	 * @generated
	 */
  EReference getContrainte_Expression();

  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.Colonne <em>Colonne</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Colonne</em>'.
	 * @see fr.n7.cONTRAINTES.Colonne
	 * @generated
	 */
  EClass getColonne();

  /**
	 * Returns the meta object for the attribute '{@link fr.n7.cONTRAINTES.Colonne#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see fr.n7.cONTRAINTES.Colonne#getName()
	 * @see #getColonne()
	 * @generated
	 */
  EAttribute getColonne_Name();

  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.Expression <em>Expression</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Expression</em>'.
	 * @see fr.n7.cONTRAINTES.Expression
	 * @generated
	 */
  EClass getExpression();

  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.Comparaison <em>Comparaison</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Comparaison</em>'.
	 * @see fr.n7.cONTRAINTES.Comparaison
	 * @generated
	 */
  EClass getComparaison();

  /**
	 * Returns the meta object for the attribute '{@link fr.n7.cONTRAINTES.Comparaison#getComparateur <em>Comparateur</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Comparateur</em>'.
	 * @see fr.n7.cONTRAINTES.Comparaison#getComparateur()
	 * @see #getComparaison()
	 * @generated
	 */
  EAttribute getComparaison_Comparateur();

  /**
	 * Returns the meta object for the attribute '{@link fr.n7.cONTRAINTES.Comparaison#getConstante <em>Constante</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Constante</em>'.
	 * @see fr.n7.cONTRAINTES.Comparaison#getConstante()
	 * @see #getComparaison()
	 * @generated
	 */
  EAttribute getComparaison_Constante();

  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.OperationBinaire <em>Operation Binaire</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Operation Binaire</em>'.
	 * @see fr.n7.cONTRAINTES.OperationBinaire
	 * @generated
	 */
  EClass getOperationBinaire();

  /**
	 * Returns the meta object for the containment reference '{@link fr.n7.cONTRAINTES.OperationBinaire#getContrainteGauche <em>Contrainte Gauche</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Contrainte Gauche</em>'.
	 * @see fr.n7.cONTRAINTES.OperationBinaire#getContrainteGauche()
	 * @see #getOperationBinaire()
	 * @generated
	 */
  EReference getOperationBinaire_ContrainteGauche();

  /**
	 * Returns the meta object for the attribute '{@link fr.n7.cONTRAINTES.OperationBinaire#getOperande <em>Operande</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Operande</em>'.
	 * @see fr.n7.cONTRAINTES.OperationBinaire#getOperande()
	 * @see #getOperationBinaire()
	 * @generated
	 */
  EAttribute getOperationBinaire_Operande();

  /**
	 * Returns the meta object for the containment reference '{@link fr.n7.cONTRAINTES.OperationBinaire#getContrainteDroite <em>Contrainte Droite</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Contrainte Droite</em>'.
	 * @see fr.n7.cONTRAINTES.OperationBinaire#getContrainteDroite()
	 * @see #getOperationBinaire()
	 * @generated
	 */
  EReference getOperationBinaire_ContrainteDroite();

  /**
	 * Returns the meta object for class '{@link fr.n7.cONTRAINTES.OperationUnaire <em>Operation Unaire</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Operation Unaire</em>'.
	 * @see fr.n7.cONTRAINTES.OperationUnaire
	 * @generated
	 */
  EClass getOperationUnaire();

  /**
	 * Returns the meta object for the attribute '{@link fr.n7.cONTRAINTES.OperationUnaire#getOperande <em>Operande</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Operande</em>'.
	 * @see fr.n7.cONTRAINTES.OperationUnaire#getOperande()
	 * @see #getOperationUnaire()
	 * @generated
	 */
  EAttribute getOperationUnaire_Operande();

  /**
	 * Returns the meta object for the containment reference '{@link fr.n7.cONTRAINTES.OperationUnaire#getContrainte <em>Contrainte</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Contrainte</em>'.
	 * @see fr.n7.cONTRAINTES.OperationUnaire#getContrainte()
	 * @see #getOperationUnaire()
	 * @generated
	 */
  EReference getOperationUnaire_Contrainte();

  /**
	 * Returns the meta object for enum '{@link fr.n7.cONTRAINTES.ComparateurType <em>Comparateur Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Comparateur Type</em>'.
	 * @see fr.n7.cONTRAINTES.ComparateurType
	 * @generated
	 */
  EEnum getComparateurType();

  /**
	 * Returns the meta object for enum '{@link fr.n7.cONTRAINTES.OperandeBinaireType <em>Operande Binaire Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Operande Binaire Type</em>'.
	 * @see fr.n7.cONTRAINTES.OperandeBinaireType
	 * @generated
	 */
  EEnum getOperandeBinaireType();

  /**
	 * Returns the meta object for enum '{@link fr.n7.cONTRAINTES.OperandeUnaireType <em>Operande Unaire Type</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for enum '<em>Operande Unaire Type</em>'.
	 * @see fr.n7.cONTRAINTES.OperandeUnaireType
	 * @generated
	 */
  EEnum getOperandeUnaireType();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  CONTRAINTESFactory getCONTRAINTESFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.EnsembleContraintesImpl <em>Ensemble Contraintes</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.EnsembleContraintesImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getEnsembleContraintes()
		 * @generated
		 */
    EClass ENSEMBLE_CONTRAINTES = eINSTANCE.getEnsembleContraintes();

    /**
		 * The meta object literal for the '<em><b>Contraintes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ENSEMBLE_CONTRAINTES__CONTRAINTES = eINSTANCE.getEnsembleContraintes_Contraintes();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.ContrainteImpl <em>Contrainte</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.ContrainteImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getContrainte()
		 * @generated
		 */
    EClass CONTRAINTE = eINSTANCE.getContrainte();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute CONTRAINTE__NAME = eINSTANCE.getContrainte_Name();

    /**
		 * The meta object literal for the '<em><b>Colonnes</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference CONTRAINTE__COLONNES = eINSTANCE.getContrainte_Colonnes();

    /**
		 * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference CONTRAINTE__EXPRESSION = eINSTANCE.getContrainte_Expression();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.ColonneImpl <em>Colonne</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.ColonneImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getColonne()
		 * @generated
		 */
    EClass COLONNE = eINSTANCE.getColonne();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute COLONNE__NAME = eINSTANCE.getColonne_Name();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.ExpressionImpl <em>Expression</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.ExpressionImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getExpression()
		 * @generated
		 */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.ComparaisonImpl <em>Comparaison</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.ComparaisonImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getComparaison()
		 * @generated
		 */
    EClass COMPARAISON = eINSTANCE.getComparaison();

    /**
		 * The meta object literal for the '<em><b>Comparateur</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute COMPARAISON__COMPARATEUR = eINSTANCE.getComparaison_Comparateur();

    /**
		 * The meta object literal for the '<em><b>Constante</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute COMPARAISON__CONSTANTE = eINSTANCE.getComparaison_Constante();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.OperationBinaireImpl <em>Operation Binaire</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.OperationBinaireImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperationBinaire()
		 * @generated
		 */
    EClass OPERATION_BINAIRE = eINSTANCE.getOperationBinaire();

    /**
		 * The meta object literal for the '<em><b>Contrainte Gauche</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference OPERATION_BINAIRE__CONTRAINTE_GAUCHE = eINSTANCE.getOperationBinaire_ContrainteGauche();

    /**
		 * The meta object literal for the '<em><b>Operande</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute OPERATION_BINAIRE__OPERANDE = eINSTANCE.getOperationBinaire_Operande();

    /**
		 * The meta object literal for the '<em><b>Contrainte Droite</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference OPERATION_BINAIRE__CONTRAINTE_DROITE = eINSTANCE.getOperationBinaire_ContrainteDroite();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.impl.OperationUnaireImpl <em>Operation Unaire</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.impl.OperationUnaireImpl
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperationUnaire()
		 * @generated
		 */
    EClass OPERATION_UNAIRE = eINSTANCE.getOperationUnaire();

    /**
		 * The meta object literal for the '<em><b>Operande</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute OPERATION_UNAIRE__OPERANDE = eINSTANCE.getOperationUnaire_Operande();

    /**
		 * The meta object literal for the '<em><b>Contrainte</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference OPERATION_UNAIRE__CONTRAINTE = eINSTANCE.getOperationUnaire_Contrainte();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.ComparateurType <em>Comparateur Type</em>}' enum.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.ComparateurType
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getComparateurType()
		 * @generated
		 */
    EEnum COMPARATEUR_TYPE = eINSTANCE.getComparateurType();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.OperandeBinaireType <em>Operande Binaire Type</em>}' enum.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.OperandeBinaireType
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperandeBinaireType()
		 * @generated
		 */
    EEnum OPERANDE_BINAIRE_TYPE = eINSTANCE.getOperandeBinaireType();

    /**
		 * The meta object literal for the '{@link fr.n7.cONTRAINTES.OperandeUnaireType <em>Operande Unaire Type</em>}' enum.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see fr.n7.cONTRAINTES.OperandeUnaireType
		 * @see fr.n7.cONTRAINTES.impl.CONTRAINTESPackageImpl#getOperandeUnaireType()
		 * @generated
		 */
    EEnum OPERANDE_UNAIRE_TYPE = eINSTANCE.getOperandeUnaireType();

  }

} //CONTRAINTESPackage
