/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage
 * @generated
 */
public interface CONTRAINTESFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CONTRAINTESFactory eINSTANCE = fr.n7.cONTRAINTES.impl.CONTRAINTESFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Ensemble Contraintes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ensemble Contraintes</em>'.
   * @generated
   */
  EnsembleContraintes createEnsembleContraintes();

  /**
   * Returns a new object of class '<em>Contrainte</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contrainte</em>'.
   * @generated
   */
  Contrainte createContrainte();

  /**
   * Returns a new object of class '<em>Colonne</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Colonne</em>'.
   * @generated
   */
  Colonne createColonne();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Comparaison</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comparaison</em>'.
   * @generated
   */
  Comparaison createComparaison();

  /**
   * Returns a new object of class '<em>Operation Binaire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Binaire</em>'.
   * @generated
   */
  OperationBinaire createOperationBinaire();

  /**
   * Returns a new object of class '<em>Operation Unaire</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Operation Unaire</em>'.
   * @generated
   */
  OperationUnaire createOperationUnaire();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  CONTRAINTESPackage getCONTRAINTESPackage();

} //CONTRAINTESFactory
