/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ensemble Contraintes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.cONTRAINTES.EnsembleContraintes#getContraintes <em>Contraintes</em>}</li>
 * </ul>
 *
 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getEnsembleContraintes()
 * @model
 * @generated
 */
public interface EnsembleContraintes extends EObject
{
  /**
   * Returns the value of the '<em><b>Contraintes</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.cONTRAINTES.Contrainte}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contraintes</em>' containment reference list.
   * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getEnsembleContraintes_Contraintes()
   * @model containment="true"
   * @generated
   */
  EList<Contrainte> getContraintes();

} // EnsembleContraintes
