/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
