/**
 * generated by Xtext 2.23.0
 */
package fr.n7.cONTRAINTES;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Unaire</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.cONTRAINTES.OperationUnaire#getOperande <em>Operande</em>}</li>
 *   <li>{@link fr.n7.cONTRAINTES.OperationUnaire#getContrainte <em>Contrainte</em>}</li>
 * </ul>
 *
 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getOperationUnaire()
 * @model
 * @generated
 */
public interface OperationUnaire extends Expression
{
  /**
	 * Returns the value of the '<em><b>Operande</b></em>' attribute.
	 * The literals are from the enumeration {@link fr.n7.cONTRAINTES.OperandeUnaireType}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Operande</em>' attribute.
	 * @see fr.n7.cONTRAINTES.OperandeUnaireType
	 * @see #setOperande(OperandeUnaireType)
	 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getOperationUnaire_Operande()
	 * @model
	 * @generated
	 */
  OperandeUnaireType getOperande();

  /**
	 * Sets the value of the '{@link fr.n7.cONTRAINTES.OperationUnaire#getOperande <em>Operande</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Operande</em>' attribute.
	 * @see fr.n7.cONTRAINTES.OperandeUnaireType
	 * @see #getOperande()
	 * @generated
	 */
  void setOperande(OperandeUnaireType value);

  /**
	 * Returns the value of the '<em><b>Contrainte</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Contrainte</em>' containment reference.
	 * @see #setContrainte(Expression)
	 * @see fr.n7.cONTRAINTES.CONTRAINTESPackage#getOperationUnaire_Contrainte()
	 * @model containment="true"
	 * @generated
	 */
  Expression getContrainte();

  /**
	 * Sets the value of the '{@link fr.n7.cONTRAINTES.OperationUnaire#getContrainte <em>Contrainte</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Contrainte</em>' containment reference.
	 * @see #getContrainte()
	 * @generated
	 */
  void setContrainte(Expression value);

} // OperationUnaire
