/*
 * generated by Xtext 2.23.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.contraintesColonnes.ui.internal.ContraintesColonnesActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CONTRAINTESExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ContraintesColonnesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ContraintesColonnesActivator activator = ContraintesColonnesActivator.getInstance();
		return activator != null ? activator.getInjector(ContraintesColonnesActivator.FR_N7_CONTRAINTES) : null;
	}

}
