/*
 * generated by Xtext 2.23.0
 */
package fr.n7.parser.antlr;

import com.google.inject.Inject;
import fr.n7.parser.antlr.internal.InternalCONTRAINTESParser;
import fr.n7.services.CONTRAINTESGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CONTRAINTESParser extends AbstractAntlrParser {

	@Inject
	private CONTRAINTESGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCONTRAINTESParser createParser(XtextTokenStream stream) {
		return new InternalCONTRAINTESParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EnsembleContraintes";
	}

	public CONTRAINTESGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CONTRAINTESGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
